'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2300
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsU
    Inherits DataSet
    
    Private tableusers As usersDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("users")) Is Nothing) Then
                Me.Tables.Add(New usersDataTable(ds.Tables("users")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property users As usersDataTable
        Get
            Return Me.tableusers
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsU = CType(MyBase.Clone,dsU)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("users")) Is Nothing) Then
            Me.Tables.Add(New usersDataTable(ds.Tables("users")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableusers = CType(Me.Tables("users"),usersDataTable)
        If (Not (Me.tableusers) Is Nothing) Then
            Me.tableusers.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsU"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsU.xsd"
        Me.Locale = New System.Globalization.CultureInfo("fa-IR")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableusers = New usersDataTable
        Me.Tables.Add(Me.tableusers)
    End Sub
    
    Private Function ShouldSerializeusers() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub usersRowChangeEventHandler(ByVal sender As Object, ByVal e As usersRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class usersDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnUID As DataColumn
        
        Private columnPWD As DataColumn
        
        Private columnDP As DataColumn
        
        Friend Sub New()
            MyBase.New("users")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property UIDColumn As DataColumn
            Get
                Return Me.columnUID
            End Get
        End Property
        
        Friend ReadOnly Property PWDColumn As DataColumn
            Get
                Return Me.columnPWD
            End Get
        End Property
        
        Friend ReadOnly Property DPColumn As DataColumn
            Get
                Return Me.columnDP
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As usersRow
            Get
                Return CType(Me.Rows(index),usersRow)
            End Get
        End Property
        
        Public Event usersRowChanged As usersRowChangeEventHandler
        
        Public Event usersRowChanging As usersRowChangeEventHandler
        
        Public Event usersRowDeleted As usersRowChangeEventHandler
        
        Public Event usersRowDeleting As usersRowChangeEventHandler
        
        Public Overloads Sub AddusersRow(ByVal row As usersRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddusersRow(ByVal UID As String, ByVal PWD As String, ByVal DP As String) As usersRow
            Dim rowusersRow As usersRow = CType(Me.NewRow,usersRow)
            rowusersRow.ItemArray = New Object() {UID, PWD, DP}
            Me.Rows.Add(rowusersRow)
            Return rowusersRow
        End Function
        
        Public Function FindByUID(ByVal UID As String) As usersRow
            Return CType(Me.Rows.Find(New Object() {UID}),usersRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As usersDataTable = CType(MyBase.Clone,usersDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New usersDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnUID = Me.Columns("UID")
            Me.columnPWD = Me.Columns("PWD")
            Me.columnDP = Me.Columns("DP")
        End Sub
        
        Private Sub InitClass()
            Me.columnUID = New DataColumn("UID", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnUID)
            Me.columnPWD = New DataColumn("PWD", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPWD)
            Me.columnDP = New DataColumn("DP", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDP)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnUID}, true))
            Me.columnUID.AllowDBNull = false
            Me.columnUID.Unique = true
        End Sub
        
        Public Function NewusersRow() As usersRow
            Return CType(Me.NewRow,usersRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New usersRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(usersRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.usersRowChangedEvent) Is Nothing) Then
                RaiseEvent usersRowChanged(Me, New usersRowChangeEvent(CType(e.Row,usersRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.usersRowChangingEvent) Is Nothing) Then
                RaiseEvent usersRowChanging(Me, New usersRowChangeEvent(CType(e.Row,usersRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.usersRowDeletedEvent) Is Nothing) Then
                RaiseEvent usersRowDeleted(Me, New usersRowChangeEvent(CType(e.Row,usersRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.usersRowDeletingEvent) Is Nothing) Then
                RaiseEvent usersRowDeleting(Me, New usersRowChangeEvent(CType(e.Row,usersRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveusersRow(ByVal row As usersRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class usersRow
        Inherits DataRow
        
        Private tableusers As usersDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableusers = CType(Me.Table,usersDataTable)
        End Sub
        
        Public Property UID As String
            Get
                Return CType(Me(Me.tableusers.UIDColumn),String)
            End Get
            Set
                Me(Me.tableusers.UIDColumn) = value
            End Set
        End Property
        
        Public Property PWD As String
            Get
                Try 
                    Return CType(Me(Me.tableusers.PWDColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableusers.PWDColumn) = value
            End Set
        End Property
        
        Public Property DP As String
            Get
                Try 
                    Return CType(Me(Me.tableusers.DPColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableusers.DPColumn) = value
            End Set
        End Property
        
        Public Function IsPWDNull() As Boolean
            Return Me.IsNull(Me.tableusers.PWDColumn)
        End Function
        
        Public Sub SetPWDNull()
            Me(Me.tableusers.PWDColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDPNull() As Boolean
            Return Me.IsNull(Me.tableusers.DPColumn)
        End Function
        
        Public Sub SetDPNull()
            Me(Me.tableusers.DPColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class usersRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As usersRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As usersRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As usersRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
