'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2379
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsL
    Inherits DataSet
    
    Private tableLessons As LessonsDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Lessons")) Is Nothing) Then
                Me.Tables.Add(New LessonsDataTable(ds.Tables("Lessons")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Lessons As LessonsDataTable
        Get
            Return Me.tableLessons
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsL = CType(MyBase.Clone,dsL)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("Lessons")) Is Nothing) Then
            Me.Tables.Add(New LessonsDataTable(ds.Tables("Lessons")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableLessons = CType(Me.Tables("Lessons"),LessonsDataTable)
        If (Not (Me.tableLessons) Is Nothing) Then
            Me.tableLessons.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsL"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsL.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableLessons = New LessonsDataTable
        Me.Tables.Add(Me.tableLessons)
    End Sub
    
    Private Function ShouldSerializeLessons() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub LessonsRowChangeEventHandler(ByVal sender As Object, ByVal e As LessonsRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class LessonsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnTitle As DataColumn
        
        Private columnDuration As DataColumn
        
        Private columnLID As DataColumn
        
        Friend Sub New()
            MyBase.New("Lessons")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property TitleColumn As DataColumn
            Get
                Return Me.columnTitle
            End Get
        End Property
        
        Friend ReadOnly Property DurationColumn As DataColumn
            Get
                Return Me.columnDuration
            End Get
        End Property
        
        Friend ReadOnly Property LIDColumn As DataColumn
            Get
                Return Me.columnLID
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As LessonsRow
            Get
                Return CType(Me.Rows(index),LessonsRow)
            End Get
        End Property
        
        Public Event LessonsRowChanged As LessonsRowChangeEventHandler
        
        Public Event LessonsRowChanging As LessonsRowChangeEventHandler
        
        Public Event LessonsRowDeleted As LessonsRowChangeEventHandler
        
        Public Event LessonsRowDeleting As LessonsRowChangeEventHandler
        
        Public Overloads Sub AddLessonsRow(ByVal row As LessonsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddLessonsRow(ByVal Title As String, ByVal Duration As Integer, ByVal LID As Integer) As LessonsRow
            Dim rowLessonsRow As LessonsRow = CType(Me.NewRow,LessonsRow)
            rowLessonsRow.ItemArray = New Object() {Title, Duration, LID}
            Me.Rows.Add(rowLessonsRow)
            Return rowLessonsRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As LessonsDataTable = CType(MyBase.Clone,LessonsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New LessonsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnTitle = Me.Columns("Title")
            Me.columnDuration = Me.Columns("Duration")
            Me.columnLID = Me.Columns("LID")
        End Sub
        
        Private Sub InitClass()
            Me.columnTitle = New DataColumn("Title", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTitle)
            Me.columnDuration = New DataColumn("Duration", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDuration)
            Me.columnLID = New DataColumn("LID", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnLID)
            Me.columnLID.AllowDBNull = false
        End Sub
        
        Public Function NewLessonsRow() As LessonsRow
            Return CType(Me.NewRow,LessonsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New LessonsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(LessonsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.LessonsRowChangedEvent) Is Nothing) Then
                RaiseEvent LessonsRowChanged(Me, New LessonsRowChangeEvent(CType(e.Row,LessonsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.LessonsRowChangingEvent) Is Nothing) Then
                RaiseEvent LessonsRowChanging(Me, New LessonsRowChangeEvent(CType(e.Row,LessonsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.LessonsRowDeletedEvent) Is Nothing) Then
                RaiseEvent LessonsRowDeleted(Me, New LessonsRowChangeEvent(CType(e.Row,LessonsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.LessonsRowDeletingEvent) Is Nothing) Then
                RaiseEvent LessonsRowDeleting(Me, New LessonsRowChangeEvent(CType(e.Row,LessonsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveLessonsRow(ByVal row As LessonsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class LessonsRow
        Inherits DataRow
        
        Private tableLessons As LessonsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableLessons = CType(Me.Table,LessonsDataTable)
        End Sub
        
        Public Property Title As String
            Get
                Try 
                    Return CType(Me(Me.tableLessons.TitleColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLessons.TitleColumn) = value
            End Set
        End Property
        
        Public Property Duration As Integer
            Get
                Try 
                    Return CType(Me(Me.tableLessons.DurationColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLessons.DurationColumn) = value
            End Set
        End Property
        
        Public Property LID As Integer
            Get
                Return CType(Me(Me.tableLessons.LIDColumn),Integer)
            End Get
            Set
                Me(Me.tableLessons.LIDColumn) = value
            End Set
        End Property
        
        Public Function IsTitleNull() As Boolean
            Return Me.IsNull(Me.tableLessons.TitleColumn)
        End Function
        
        Public Sub SetTitleNull()
            Me(Me.tableLessons.TitleColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDurationNull() As Boolean
            Return Me.IsNull(Me.tableLessons.DurationColumn)
        End Function
        
        Public Sub SetDurationNull()
            Me(Me.tableLessons.DurationColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class LessonsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As LessonsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As LessonsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As LessonsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
